name: rinha
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  postgres:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  uuid: ^4.0.0
